# configs/configs-cleanunet2/cleanunet2-paper-exact.yaml
# EXACT configuration matching CleanUNet 2 paper specifications

# Network configuration - EXACT paper defaults
network_config:
  # CleanUNet parameters (EXACT from paper Table hyperparameters)
  cleanunet_input_channels: 1
  cleanunet_output_channels: 1
  cleanunet_channels_H: 64              # EXACT paper default
  cleanunet_max_H: 768                  # EXACT paper default  
  cleanunet_encoder_n_layers: 8         # EXACT paper default
  cleanunet_kernel_size: 4              # EXACT paper default
  cleanunet_stride: 2                   # EXACT paper default
  cleanunet_tsfm_n_layers: 5            # EXACT paper default
  cleanunet_tsfm_n_head: 8              # EXACT paper default
  cleanunet_tsfm_d_model: 512           # EXACT paper default
  cleanunet_tsfm_d_inner: 2048          # EXACT paper default
  
  # CleanSpecNet parameters (EXACT from paper)
  cleanspecnet_input_channels: 513      # From 1024 FFT
  cleanspecnet_num_conv_layers: 5       # EXACT paper default
  cleanspecnet_kernel_size: 4           # EXACT paper default
  cleanspecnet_stride: 1                # EXACT paper default
  cleanspecnet_conv_hidden_dim: 64      # EXACT paper default
  cleanspecnet_num_attention_layers: 5  # EXACT paper default
  cleanspecnet_num_heads: 8             # EXACT paper default
  cleanspecnet_hidden_dim: 512          # EXACT paper default
  cleanspecnet_dropout: 0.1             # EXACT paper default

# Training configuration - EXACT from paper
# "The CleanSpecNet is trained to minimize Eq. (1), with a batchsize of 64 and 1M iterations"
# "The CleanUNet 2 is trained to minimize the full or high-band losses described in Section 2.4, with a batchsize of 32 and 500K iterations"

# Two-stage training parameters
stage1_cleanspecnet:
  batch_size: 4                      # EXACT from paper
  iterations: 1000000                   # EXACT from paper (1M iterations)
  learning_rate: 0.0002                 # EXACT from paper (2e-4)
  optimizer: "adam"
  betas: [0.9, 0.999]                   # EXACT from paper
  scheduler: "linear_warmup_cosine"     # EXACT from paper
  warmup_ratio: 0.05                    # EXACT from paper (5%)

stage2_cleanunet2:
  batch_size: 32                        # EXACT from paper
  iterations: 500000                    # EXACT from paper (500K iterations)
  learning_rate: 0.0002                 # EXACT from paper (2e-4)
  optimizer: "adam"
  betas: [0.9, 0.999]                   # EXACT from paper
  scheduler: "linear_warmup_cosine"     # EXACT from paper
  warmup_ratio: 0.05                    # EXACT from paper (5%)

# Data configuration
trainset:
  csv_path: "data/training_pairs_16khz.csv"

valset:
  csv_path: "data/evaluation_pairs_16khz.csv"

# Audio processing settings - EXACT from paper
sample_rate: 16000                      # EXACT from paper
n_fft: 1024                            # EXACT from paper (typical neural vocoder STFT parameters)
hop_length: 256                        # EXACT from paper  
win_length: 1024                       # EXACT from paper
power: 1.0                             # Linear magnitude
max_length: 160000                     # 10 seconds at 16kHz (paper uses 10-second clips)

# Loss configuration - EXACT from paper
loss_config:
  ell_p: 1                             # EXACT from paper
  ell_p_lambda: 1                      # EXACT from paper
  stft_lambda: 1                       # EXACT from paper
  stft_config:
    sc_lambda: 0.5                     # EXACT from paper
    mag_lambda: 0.5                    # EXACT from paper
    band: "full"                       # Paper tests both "full" and "high"
    hop_sizes: [50, 120, 240]          # EXACT from paper
    win_lengths: [240, 600, 1200]      # EXACT from paper
    fft_sizes: [512, 1024, 2048]       # EXACT from paper

# System settings
num_workers: 8                         # EXACT from paper (8 NVIDIA V100 GPUs)
save_path: "outputs"
device: "cuda"

# Evaluation settings (for testing)
evaluation:
  metrics: ["pesq_wb", "pesq_nb", "stoi", "mos_pred"]
  save_audio_samples: true
  
# Model identification
model_name: cleanunet2
description: "EXACT CleanUNet 2 implementation matching paper specifications"
paper_reference: "CleanUNet 2: A Hybrid Speech Denoising Model on Waveform and Spectrogram"
training_mode: "two_stage"             # Enable two-stage training


